---
title: Supporting Seed Systems for Development
author: BACOU, Melanie
date: Last updated on `r Sys.Date()` -- CODES AND NOTES
description: Analysis for S34D field surveys.
site: bookdown::bookdown_site
output: bookdown::gitbook
bibliography: biblio.bib
---

# Objectives

This notebook summarizes results from the 2020 S34D field surveys. 

The objective of this activity is to understand the operational efficiency and profitability of seed producer groups across different environments (multiple geographies, policy and regulatory systems). The farmers in the surveyed groups produce **certified seeds** as well as **high-quality informal seeds** that go through internal seed quality assurance mechanisms. 

We have chosen several countries that are at different stages of agricultural transformation and with varying degrees of seed systems maturity. Comparing and contrasting these seed producer clubs within and across their respective contexts can help guide development partners in designing interventions and inform policy making and seed system regulations.

The analysis is split by country, with a cross-country evaluation once all survey results have been compiled. R code chunks are shown for reproducibility.


```{r setup, message=F}

library(lubridate)
library(kableExtra)
library(viridisLite)
library(scales)
library(ggplot2)
library(terra)
library(data.table)
library(ttt)
library(thematic)
library(showtext)
library(ggalluvial)
library(GGally)

knitr::opts_chunk$set(fig.height=3, fig.width=5, dpi=220, 
  fig.path="fig/", fig.showtext=TRUE, include=TRUE, 
  error=FALSE, warning=FALSE, message=FALSE)

# Helper - Default FtF colors for plots
pal <- c("#4799b5", "#94a545", "#d37d28", "#8B1E3F", "#403b33")

thematic_on("transparent", "#2f2f29", c("#4799b5", "#e6e7e8"),
  font_spec(c("Roboto Condensed", "Roboto")),
  qualitative = alpha(pal, .9))

theme_def <- function(
  base_size = 7, 
  base_family = "Roboto Condensed",
  base_fill = "transparent", ...) theme_minimal(base_size, base_family) +
  theme(
    panel.background = element_rect(fill=base_fill, color=NA),
    plot.background = element_rect(fill=base_fill, color=NA),
    legend.box.background = element_rect(fill=base_fill, color=NA),
    text = element_text(lineheight=.8),
    plot.title = element_text(size=base_size+1),
    plot.subtitle = element_text(color="#4799b5", size=base_size),
    strip.text = element_text(face="bold", hjust=0, size=base_size),
    axis.text = element_text(size=base_size),
    axis.title = element_text(hjust=0),
    legend.key.width = unit(.8, "line"),
    legend.key.height = unit(.8, "line")
  ) + theme(...)

# Helper - Default theme for tables
kbl <- function(...) kableExtra::kbl(...) %>% 
  kable_styling(
    bootstrap_options=c("condensed", "responsive", "striped", "hover"), 
    font_size=14)

# Helper - Print contingency table with chisq tests
options(ttt.theme="booktabs") 
ttt_ftable <- function(data, vars, ...) {
  stopifnot(length(vars)==3)
  dt = data[, .SD, .SDcols=vars]
  N = nrow(dt)
  dt = table(dt)
  test = mantelhaen.test(dt)
  dt = dt %>%
    prop.table() %>%
    addmargins(...) %>%
    ftable()
  names(attr(dt, "row.vars")) = vars[1:2]
  dt = round(100*dt, digits=1)
  ttt(dt,
    caption="Contingency Table (% of respondents)",
    footnote=paste(
      "N =", N,
      "| Mantel-Haenszel chi-squared =", comma(test[[1]], acc=.01),
      "| p-value = ", comma(test[[3]], acc=.0001))
  )
}

```

